name: Deploy
on:
  workflow_dispatch:
    inputs:
      modules:
        description: 'Modules to deploy (comma-separated). Leave blank for all.'
        required: false
permissions:
  contents: read
  packages: write
jobs:
  deploy:
    uses: codice/release-pipelines/.github/workflows/maven-manual-deploy.yml@main
    with:
      modules: ${{ inputs.modules }}
